name: <script-name>
env: 
  working_dir: <script-subdirectory>
# Controls when the workflow will run
on:
  # triggers may change as pipeline is updated to rely more on ref head conditionals in later steps
  push:
    branches: [ dev, main ]
    paths:
      - ${{ env.WORKING_DIR }}
    paths-ignore:
      - '**.md'
    


jobs:
  job1:
    name: Run Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: |
          echo "${working_dir}"

      - name: Sparse Checkout
        uses: gogaille/sparse-checkout@v0.1
        with:
          patterns: "${working_dir}/"
          
      - name: Run Pester Tests
        run: |
          pwsh -Command "${working_dir}/run-pester-tests.ps1"
          
      - name: Check dir contents
        run: |
          ls ${working_dir}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: repo_files
          path: |
            ${{ github.workspace }}
            !**/run-pester-tests.ps1
            !**/tests/*
            !README.md
            !.github
          if-no-files-found: error

  job2:
    name: Deploy to BRKAZHYBWRK1A
    needs: job1
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, azhybwrk1a ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: repo_files
          path: C:\script_files
          
  job3:
    name: Deploy to BRKAZHYBWRK1B
    needs: job1
    if: github.ref == 'refs/heads/main'
    runs-on: [ self-hosted, azhybwrk1b ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: repo_files
          path: C:\script_files